#!/usr/bin/env php
<?php
/**
 * SkeekS Application Initialization Tool
 *
 * php init help
 * php init install --autoremove --unlock
 * php init remove
 *
 * @author Semenov Alexander <semenov@skeeks.com>
 * @link http://skeeks.com/
 * @copyright 2010-2014 SkeekS (Sx)
 * @date 19.02.2015
 * @since 1.0.0
 */
define("ROOT_DIR", realpath(__DIR__));

$installClassFile = __DIR__ . '/install/Install.php';
if (!file_exists($installClassFile))
{
    echo "Установочный пакет не найден, пробуем установить его с использованием git" . PHP_EOL;

    system("cd " . ROOT_DIR . "; mkdir install");
    system("cd " . ROOT_DIR . "; git clone http://git.skeeks.com/skeeks/cms-install.git install");
}

if (!file_exists($installClassFile))
{
    die("Не найден установочный скрипт, скачайте его в диррикторию install из http://git.skeeks.com/skeeks/cms-install.git");
}

include $installClassFile;

$config = (array) include __DIR__ . '/install/config.php';
$install = new Install($config);
$install->run();